algoritmo "calcula_idade"
// Autor : Winderson
// Data : 23/06/2024
var
ano,aniversario,idade:inteiro
inicio
//solicita ano atual
escreval("qual o ano atual")
leia(ano)
//solicita ano de nascimento
escreval("qual o ano do seu aniversário")
leia(aniversario)
//efetua calculo da idade
idade<-ano-aniversario
//apresenta idade
escreval("você tem ",idade," anos de idade")
fimalgoritmo
