algoritmo "nome"
// Autor :Winderson
// Data : 21/06/2024
var
nome:caractere
inicio
//solicita o nome do usuário
escreval("########################################")
escreval("Por favor insira o seu nome")
escreval("########################################")
escreval("  ")
//lê o nome do usuário
leia(nome)
//escreve o nome do usuário
escreval("Seja muito bem-vindo ", nome)
fimalgoritmo
