algoritmo "leitor_dinheiro"
// Autor : Winderson
// Data : 21/06/2024
var
dinheiro:real
inicio
//solicita quanto dinheiro tem
escreval("digite quanto de dinheiro você quer converter em dólares ")
//lê dinheiro
leia(dinheiro)
//apresenta para o usuário quanto de dinheiro ele tem em sua conversão par dólar sem alterar a variável
escreval("você possui atualmente o valor para comprar U$ ", dinheiro/3.45)
fimalgoritmo
