algoritmo "a sua escolha-Acabou!"
// Autor : Winderson
// Data : 07/07/2024
var
n1,n2,i:inteiro
inicio
//recolhe informações necessárias
escreva("informe o valor inicial: ")
leia(n1)
escreva("informe o valor final: ")
leia(n2)
escreva("informe o valor de incremento: ")
leia(i)
//executa o cálculo no loop com os valores informados
enquanto n1<=n2 faca
    escreval(n1)
    n1<-n1+i
fimenquanto
escreval(" Acabou!")
fimalgoritmo
