algoritmo "antecessor e sucessor"
// Autor: Winderson
// Data: 21/06/2024
var
num: inteiro
inicio
//solicita um número
escreval("por favor informe um número inteiro que lhe daremos seu sucessor e seu antecessor ")
//lê o número
leia(num)
//escreve o valor e também calcula e escreve seu antecessor e sucessor sem alterar a variável
escreval("o número digitado foi:", num , " seu antecessor é:", num-1," e seu sucessor é:", num+1)
fimalgoritmo
