algoritmo "dobro e terça"
// Autor : Winderson
// Data : 21/06/2024
var
num:real
inicio
//solicita um valor
escreval("por favor informe um número para lhe apresentarmos seu dobro e sua terça")
//lê o valor
leia(num)
//escreve o valor e também seu dobro e sua terça sem alterar a variável
escreval("o número digitado foi:", num , " seu dobro é:", num+num," e sua terça é:", num/3)
fimalgoritmo
