algoritmo "soma de 7 números"
// Autor : Winderson
// Data : 07/07/2024
var
n,i,soma:inteiro
inicio
//atribui valor para as variáveis
soma<-0
i<-0
//realiza o cálculo
enquanto i<>7 faca
         escreva("informe um número para a soma: ")
         leia(n)
         soma<-soma+n
         i<-i+1
fimenquanto
//mostra o resultado
escreval("a soma de dos sete números é:",soma)
fimalgoritmo
