algoritmo "distancia percorrida"
// Autor : Winderson
// Data : 27/06/2024
var
km:inteiro
inicio
//solicita km e le km
escreval("por favor informe a distância que deseja percorrer")
leia(km)
//verifica se km é menor do que 20 sendo aplica o valor e apresenta
se km < 20 entao
   Escreval("sua viagem ficara no valor de RS",km*0.50)
//se não aplica o valor de mais km e apresenta
senao
   escreval("sua viagem ficara no valor de RS",km*0.45)
   fimse
fimalgoritmo
